### ISSUE TITLE
Link to dataset broken

### ISSUE THREAD

**Issue by walkingintopeople** [robertlayton/authorship_tutorials#1]
Link to dataset (http://ubuntuone.com/7jjipUOm4w4lVOvfLVM9Kg) is broken. It should be possible to upload the dataset to github (depending on license, I suppose)

**Comment by robertlayton** [comment]
Thanks for letting me know. I'm not sure if I can, but I'll check and upload if possible.

Edit: It appears that they are "free as in speech", so I'll rehost them soon on github.
https://www.gutenberg.org/wiki/Gutenberg:No_Cost_or_Freedom%3F

**Comment by robertlayton** [comment]
Fixed! Sorry it took so long, I've been away. The dataset is saved as a zip in the git repo, but it is unlikely to change.

Thanks for reporting!

**Comment by walkingintopeople** [comment]
Thank you very much. This tutorial has been invaluable for me to figure out
why my own implementations didn't work.
